### ISSUE TITLE
First Suggestion and an issue!

### ISSUE THREAD

**Issue by mihal190** [jetelain/AceArsenalExtended#1]
The Issue: After re-connecting to server, your customized uniform using textureoptions is reset
The suggestion: you can't use this awesome option in editor which is quite sad, ACE arleady added ACE Arsenal for editor

**Comment by jetelain** [comment]
Hi, I'm aware of this issue.  
I've planned to work on it !
There is multiple ways to fix this, but I need to do intensive testing to find which one is the more reliable.
