### ISSUE TITLE
Loadouts not saving?

### ISSUE THREAD

**Issue by rudy123a** [jetelain/AceArsenalExtended#10]
So my group has started using this arsenal, and once everyone made loadouts and logged off it seems once they load back in the loadouts are no longer functional, they're blacked out like some of the stuff is not in the arsenal. Once they load the loadout, the shirt and sometimes the helmet aren't the correct configuration they selected.

**Comment by jetelain** [comment]
Hi, good news, thanks to @BrettMayson, it's going to be possible
- https://github.com/CBATeam/CBA_A3/pull/1548
- https://github.com/acemod/ACE3/pull/8923
