### ISSUE TITLE
Feature Request: Weapons, RHS Support

### ISSUE THREAD

**Issue by Quailsnap** [jetelain/AceArsenalExtended#11]
Lots of vanilla weapons with multiple variants that could be cleaned up using this solution. Would a similar config work for CfgWeapons?

Further, RHS has a ton of uniform variants, especially for the Russian uniforms. Condensing those into the submenu buttons would be super handy. I'm willing to do the work and make a pull, but I want to ask feasibility first -- is there anything in the way?

**Comment by jetelain** [comment]
Hi, It's possible, I was planning to add support for it. Help is welcome !

**Comment by Ghost-JB** [comment]
I recognize this is an older issue, at this point, but seeing no other comments to this effect: ACE-AX is currently capable of handling weapon variants, in precisely the same way it does uniforms and other pieces of gear. I'm using the method of a "XtdGearModels.hpp" and "XtdGearInfos.hpp". Build up the options you want in the 'models' file under "class XtdGearModels", then list out all of the relevant classes (of uniforms, ... , and even weapons) with each one's particular values in 'infos' under "class XtdGearInfos", and viola!

Also, I'm... most of the way through an RHS compat, myself, which I should probably share here when done. In this compat I've collapsed uniforms, vests, headgear, and even weapons. It is amazing to have so many options compacted into so little list-space :D

**Comment by fire-391** [comment]
> I recognize this is an older issue, at this point, but seeing no other comments to this effect: ACE-AX is currently capable of handling weapon variants, in precisely the same way it does uniforms and other pieces of gear. I'm using the method of a "XtdGearModels.hpp" and "XtdGearInfos.hpp". Build up the options you want in the 'models' file under "class XtdGearModels", then list out all of the relevant classes (of uniforms, ... , and even weapons) with each one's particular values in 'infos' under "class XtdGearInfos", and viola!
> 
> Also, I'm... most of the way through an RHS compat, myself, which I should probably share here when done. In this compat I've collapsed uniforms, vests, headgear, and even weapons. It is amazing to have so many options compacted into so little list-space :D

Have you finished the RHS compat yet? Still waiting on this and a fleshed out Tier One implementation to add it to our units mod line.

**Comment by PetMudstone** [comment]
I'm working on RHS support on my own fork. While I don't have anything but the SCAR-Hs covered yet I do plan on addressing all RHS weapons at some point. 

Check it out here: https://github.com/PetMudstone/AceArsenalExtended

**Comment by PetMudstone** [comment]
I have a [patch for RHS](https://steamcommunity.com/sharedfiles/filedetails/?id=2944314446) out on the workshop that has support for its weapons now!

**Comment by Quailsnap** [comment]
I've been using it and it's a lifechanger. Thank you so much!
