### ISSUE TITLE
L85A2 Foregrip RIS

### ISSUE THREAD

**Issue by JoshPiper** [jetelain/AceArsenalExtended#16]
The foregrip L85 should be labelled under RIS.

Assignees:
Labels:

**Comment by jetelain** [comment]
Hi, I think the issue is in one of the third party compat mod.

**Comment by JoshPiper** [comment]
Aye, it was meant to go into [my fork](https://github.com/JoshPiper/AceArsenalExtended/tree/compat/cup) / [forked issues](https://github.com/JoshPiper/AceArsenalExtended/issues) Not sure why GitHub put it here, nor how I didn't notice it in a year.
