### ISSUE TITLE
Could you guys help me out?

### ISSUE THREAD

**Issue by deBearN** [jetelain/AceArsenalExtended#19]
if there's any other place to reach you guys out like a discord or something it would be easier
i recently created a compat of your mod to the BRAF mod (Brazillian Armed Forces)

/// What they have

They have a system where you can add your name to the Uniform via a function/script

And a system based on ranks,brevet,branch, where it's a hidden selection with a specific texture.
there's the rank hidden selection with 13 options of hidden textures to have all ranks.

/// What i'm trying to do

I wanted to know if there's any chance that i can make a button like the ones i use to execute the commands to create those things

like, a button written "Name" on it, that when you press it it executes the function/script that selects the player name and put it into the Uniform

or 13 buttons for the ranks so i can click on like Soldier and it executes
this command
_this setObjectTextureGlobal [7,"Path to paa"]    //7 being the number of the hidden selection i'm selecting.

I did create several uniforms with all combinations utlizing a script i did in C++ that looped everything until every possibility was complete, the problem was that it had over 60 million lines and Arma took to long to read it all (1 million per 5 minutes)

/// Final words

if you guys can lead my way or help me in any way achieving this -> Button that executes those scripts in the same UI as the uniform i have your mod on, i would be grateful.

if in case of any response i can help clarify things further like, where the function is, how do you call it and stuff like that.

**Comment by jetelain** [comment]
Hi,

I can be reached on Arma Discord or Arma Mod France Discord (https://discord.gg/AQn2qydpZ7), look for "GrueArbre".

For Ranks and Names you can create "Texture options" to avoid create so many combinations.

If you give me some samples I can write you the required configuration.

Anyway for Name, you will have one button for each name. But I can look to allows some custom logic for some options selection (I was studying this for ranks and blood patches).
