### ISSUE TITLE
Avoid dependency on mods, to allow "all-in-one" compatibility

### ISSUE THREAD

**Issue by jetelain** [jetelain/AceArsenalExtended#2]
Compatibility with a large number of mods would be really great, but with current approach it would leads to publish a lot of mods on the workshop, which is not sustainable.

To address this, the dependency on mod pbo should not be required.

The idea is to create a secondary way to annotate configs with a new `XtdGearInfos` class.

```cpp
class XtdGearInfos
{
  class CfgWeapons
  {
    class Xxxx
    {
      model = "xxxx";
      ...
    };
  };
};
```

It should be possible with really little refactoring. 

It will also avoid headaches with mods class hierarchy.

**Comment by JCalebBR** [comment]
It's 2025. You can now add `skipWhenMissingDependencies = 1` to a `CfgPatches`. Self explanatory, but just in case, it will skip loading of that pbo if its dependencies are missing AND won't give the user an error.
