### ISSUE TITLE
Feature Request: ability to choose length of action for fnc_changeGear

### ISSUE THREAD

**Issue by Ghost-JB** [jetelain/AceArsenalExtended#20]
Currently, the length of time that any gear change made through the ACE self-interact menu takes is determined in the script and is unchangeable.

The request is to be able to pass a specified duration to the script via another param or config entry, similar to the "actionLabel=" entry.

I encountered this as an issue while adding some features to my community's uniform pack. We wanted the ability to "turn off our active ear protection (Peltors)" in the event that we were operating in high-noise environments (such as near helicopters). Our solution was to simply double up our headgear classes, with one class having "ace_hearing_lowerVolume=0" (to represent on) and the other having a higher value (to represent the active listening being turned off), and use the ACE-AX gear chang function to easily swap them out. It then became apparent that the timer is hard coded, and it does not take 2 seconds to turn off a set of Peltors.

**Comment by jetelain** [comment]
Hi, I will add an option for that !

**Comment by jetelain** [comment]
It's also available on Workshop.

You can set `changedelay` within option, or define a different value for each value.
