### ISSUE TITLE
Issue: Listing only 1 item from customization sometimes causes other variants to dissapear

### ISSUE THREAD

**Issue by mihal190** [jetelain/AceArsenalExtended#3]
While changing variants in arsenal, trough normal system not texture options, items might dissapear if arsenal doesn't have them listed, it only happens when you are switching very fast or clicking by the edge of buttons, doing it nice and slowly lowers chances for this to appear, but the problem still exists

**Comment by jetelain** [comment]
Might be fixed by #7

**Comment by jetelain** [comment]
Fix of #7 have been published, is the issue still here ?
