### ISSUE TITLE
ACEAX allows clients to choose items that shouldn't be available.

### ISSUE THREAD

**Issue by PetMudstone** [jetelain/AceArsenalExtended#37]
When ACEAX and relevant compatibility patches are enabled, it is possible to select items through the pop-up window that appears from the bottom of the arsenal interface even if said items wouldn't normally be available from the arsenal.

Backpack tab during an operation without ACEAX:
![WithoutACEAX](https://user-images.githubusercontent.com/38266309/222995390-a15c2ac0-1491-451b-a3ca-786f65c1ced2.png)

Backpack tab during an operation with ACEAX and a compat patch for vanilla enabled:
![WithACEAX](https://user-images.githubusercontent.com/38266309/222995400-237b752e-d37b-4cc3-a27e-3c7d72e73ab2.png)

**Comment by jetelain** [comment]
Hi, New version with the feature have been published on Workshop
