### ISSUE TITLE
Ace Extended Hidden Options

### ISSUE THREAD

**Issue by Jerry442** [jetelain/AceArsenalExtended#44]
Hopefully there is already a way to do what I want, but I'm here just asking if you know how it would be possible or if not would you give me permission to modify and then pull request a change to this project to implement the change I seek.

I have generated configs to allow me to create all the possible variants I need for a fully customisable vest, however I don't want these options to all show up in my mod unless you have ace extended loaded (I don't want to create a separate compac) and instead just want a way to allow scopeArsenal=1 items to still be recognised by ace extended. Or another way for this mod to detect the my variants and allow them to be accessed while having ace arsenal itself not detect them and therefore they will only show up when ace extended is loaded, but the classes still exist so anyone regardless of if they have ace extended or not they will still be able to see these variants when someone else has them loaded.

Essentially I want to provide the options to people with the mod loaded, but not flood peoples arsenals if they don't have it loaded.

I know this is more than possible with an independent compac that requires ace extended, but I'd love to keep it all within the single project, so my main questions are:
Is this already possible and if so how?
If it's not possible where in your code do you detect all the possible variants in which I could implement another scopeValue it would accept for example extendedScope = 2 in which if it detects this it will add it to the possible variants regardless of the scopeArsenal value.

Thanks for your time Jerry

**Comment by jetelain** [comment]
Hi,
You can modify and make a pull request.
In current version you can still achieve the same with arsenalscope=1 on configs, and set ingame=1 on related options.
Before PR #39, it use to work with all options. This PR restrict to allow items in arsenal, and the list is based on configs with arsenalscope=2 (or assimilated). 
You may add something like ingame=1 but that only allow to bypass _allowedItems restriction on an option without ingame actions.
