### ISSUE TITLE
Problem with texture options in the latest update

### ISSUE THREAD

**Issue by deBearN** [jetelain/AceArsenalExtended#53]
I added the Ace Arsenal Extended to the BRAF (Brazillian Armed Forces) Mod and i mostly utilize textureoptions as a way of changing the skins and i've received complains of the modification made using the texture options resetting when swapping Vests and Backpacks

In more details if i change the textures in the uniform and then swap either my backpack or my vest they reset to the default pattern used by the base uniform, opening the uniform tab back adds the modifications back but several users noted this problem with annoyance 

the same issue can be seen with the USP fork of the Arsenal Extended with the flags and patches that uses the texture options to customize them

Upon further testing if i swap to a Vest that utilizes Ace Arsenal Extended the issue appears to disappear? if i select a vest that doesn't uses AAE the texture altered with texture options disappear if i THEN select a vest or backpack that utilizes AAE the textures modified with texture options starts working again

The problems stated above can be seen in the following video https://www.youtube.com/watch?v=Xf93DfkUVW4

**Comment by jetelain** [comment]
Thank you for the report. ACE has changed the way some items are set, I'm working on a fix.

**Comment by jetelain** [comment]
Fix have been published on the workshop

**Comment by deBearN** [comment]
> Fix have been published on the workshop

God
