### ISSUE TITLE
Feature Request: add Hiddenselection Materials to texture options

### ISSUE THREAD

**Issue by mihal190** [jetelain/AceArsenalExtended#6]
Add option to use custom materials for textureopitons:

Original
class Texture{texture = Texture.paa";};

Suggested
class Texture{texture = "Texture.paa";Material = Texture.rvmat";};

**Comment by jetelain** [comment]
Feature published on Workshop, let me know if it's ok for you

**Comment by mihal190** [comment]
// material = = "path\to\material.rvmat"; (default is "\a3\data_f\default.rvmat")

Needs to be changed, example of material in regular CfgWeapons
hiddenSelectionsMaterials[] = {"sgu_russia\altyn\data\cover_Velcro.rvmat"};	
if this parameter is not present it should be ignored, as of now, forcing default.rvmat breaks every model in the game
