### ISSUE TITLE
Changing options for items should update the classname shown by tooltip and obtained via Ctrl + C.

### ISSUE THREAD

**Issue by PetMudstone** [jetelain/AceArsenalExtended#62]
### The classname doesn't appear in tooltips.
When using ACEAX, if you change the options for a given item the classname shown whenever you mouse over the item in the arsenal list classname of the original variant of the item as seen before you started adjusting options. 

Notably, if you change between item tabs and go back the classname shown in the tooltip will be updated to match the new variant you have selected. I.E. if you are looking at the vanilla "Combat Helmet" with a classname of `H_HelmetB` and use options to switch to the "Combat Helmet (Tropic)" variant with a classname of `H_HelmetB_tna_F`, the classname shown when mousing over and which will be copied to the clipboard will still be `H_HelmetB` until you change tabs and return to the tab you were in before, at which point the given classname will be refreshed and properly show up as `H_HelmetB_tna_F`.

### The classname should be copy-able right after changing an option.

Furthermore, if you use CTRL + C in an attempt to copy the classname of the item you updated right after changing an option it will instead export your loadout to the keyboard. Notably, if you click back on an item's entry and input CTRL + C  it **will** actually copy the updated classname of the new item that is occupying the entry after options were changed. It would be helpful to people making arsenal lists and mod makers if selecting an option made CTRL + C export the classname to the clipboard.

**Comment by jetelain** [comment]
Hi,
Both points have been fixed (#65 and #64). I have also fixed the icon of the selected item which was not updated.
